requires 'perl', '5.40.0';
requires 'File::ShareDir', '1.00';

on 'configure' => sub {
    requires 'Alien::Xmake::Base', '0';
};

on 'build' => sub {
    requires 'ExtUtils::InstallPaths', '0.002';
    requires 'ExtUtils::Install', '2.00';
};
